name: Release Wheels

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write


jobs:

  native-wheels:
    uses: ./.github/workflows/build-wheels.yml
    with:
      python-version: '3.14'

  release:
    needs:
      - native-wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: softprops/action-gh-release@v3.0.1
        with:
          generate_release_notes: true
      - uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Upload wheels to release
        run: |
          set -eu
          find dist/wheels-* -type f -name "*.whl" -print0 | \
            xargs -0 -r gh release upload "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
